name: looma-core-test

services:
  postgres:
    image: postgres:16-alpine
    container_name: looma-postgres-test
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: looma_dev
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

  mongo:
    image: mongo:7.0
    container_name: looma-mongo-test
    ports:
      - "27018:27017"
    volumes:
      - mongo_test_data:/data/db

volumes:
  postgres_test_data:
  mongo_test_data:

