name: looma-core

services:
  postgres:
    image: postgres:16-alpine
    container_name: looma-postgres
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${POSTGRES_DB_PORT_EXTERNAL}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:7.0
    container_name: looma-mongo
    env_file: .env
    ports:
      - "${MONGO_DB_PORT_EXTERNAL}:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data: